# Generated by Django 5.2.1 on 2025-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_attendance_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
