# Generated by Django 5.2.1 on 2025-07-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
