# Generated by Django 5.2.1 on 2025-07-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
